Repository fosslight/fosslight_source_scanner, pull requests merged in 2021-08, with the labels that each got.

#25 Merge init_log & init_log_item functions
  src/fosslight_source/convert_scancode.py
  src/fosslight_source/run_scancode.py
  tests/cli_test.py
  tox.ini
Labels: chore

#28 Add option for printing matched text
  src/fosslight_source/_license_matched.py
  src/fosslight_source/_parsing_scancode_file_item.py
  src/fosslight_source/convert_scancode.py
  src/fosslight_source/run_scancode.py
  tox.ini
Labels: enhancement, minor

#29 Set condition to use FOSSLight Util v1.1.0 or later
  requirements.txt
  src/fosslight_source/_help.py
Labels: documentation, chore

#31 Print help message when p option is missing
  src/fosslight_source/convert_scancode.py
Labels: chore

#32 Remove duplicates from matched file
  src/fosslight_source/_license_matched.py
Labels: chore
