Repository fosslight/fosslight_source_scanner, pull requests merged in 2021-07, with the labels that each got.

#21 Update version in setup.py when release
  .bumpversion.cfg
  .github/workflows/publish-release.yml
  .reuse/dep5
  MANIFEST.in
  README.md
  docs/Guide_virtualenv.md
  docs/Guide_virtualenv_Kor.md
  docs/README_Kor.md
  docs/img/fosslight_source.png
Labels: chore, documentation

#22 Remove warning in publish-release.yml
  .github/workflows/publish-release.yml
Labels: chore

#24 Fix a bug related Release actions
  .github/workflows/publish-release.yml
Labels: bug fix
