Repository fosslight/fosslight_source_scanner, pull requests merged in 2021-11, with the labels that each got.

#41 Fix url for User Guide
  README.md
Labels: documentation

#43 Add python version to github PR action
  .github/workflows/pull-request.yml
  tox.ini
Labels: chore

#48 Add scanoss.py as a scanner
  setup.py
  src/fosslight_source/_help.py
  src/fosslight_source/_parsing_scancode_file_item.py
  src/fosslight_source/_parsing_scanoss_file.py
  src/fosslight_source/_scan_item.py
  src/fosslight_source/cli.py
  src/fosslight_source/run_scancode.py
  src/fosslight_source/run_scanoss.py
  tests/cli_test.py
Labels: enhancement
