Repository fosslight/fosslight_source_scanner, pull requests merged in 2021-06, with the labels that each got.

#12 Add files for reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
  tox.ini
Labels: documentation

#13 Add a reuse badge
  README.md
  docs/README_Kor.md
Labels: documentation

#14 Remove click from requirement.txt
  requirements.txt
Labels: chore

#15 Change OSS report name to FOSSLight report
  README.md
  docs/README_Kor.md
  src/fosslight_source/_help.py
  src/fosslight_source/convert_scancode.py
  src/fosslight_source/run_scancode.py
  tests/cli_test.py
  tox.ini
Labels: chore, documentation

#16 Change the name to FOSSLight Source Scanner
  CONTRIBUTING.md
  README.md
  docs/README_Kor.md
  setup.py
Labels: documentation

#17 Delete unnecessary lines at tox.ini
  tox.ini
Labels: chore

#20 Print the matched text for unknown spdx
  LICENSES/LicenseRef-MIT-like.txt
  src/fosslight_source/_parsing_scancode_file_item.py
  src/fosslight_source/run_scancode.py
  tests/cli_test.py
  tests/test_files/test_known_spdx.txt
  tests/test_files/test_unknown_spdx.txt
Labels: enhancement, minor
