Repository fosslight/fosslight_source_scanner, pull requests merged in 2022-06, with the labels that each got.

#75 Add yaml format for FOSSLight Report
  src/fosslight_source/_help.py
  src/fosslight_source/cli.py
  src/fosslight_source/run_scancode.py
Labels: enhancement

#76 update minimum version of fosslight_util
  requirements.txt
Labels: chore

#77 Fix typecode-libmagic-from-sources installation bug
  requirements.txt
Labels: bug fix

#79 Add option for time out
  src/fosslight_source/_help.py
  src/fosslight_source/cli.py
  src/fosslight_source/run_scancode.py
Labels: enhancement
