Repository fosslight/fosslight_source_scanner, pull requests merged in 2022-01, with the labels that each got.

#55 Add package to fix installation errors
  requirements.txt
Labels: bug fix

#56 Update README.md to add description for SCANOSS
  README.md
Labels: documentation

#57 Add the -v option to print the installed version of FOSSLight Source Scanner
  requirements.txt
  src/fosslight_source/_help.py
  src/fosslight_source/cli.py
  src/fosslight_source/convert_scancode.py
Labels: chore

#58 Add license reference column
  src/fosslight_source/_scan_item.py
  src/fosslight_source/cli.py
  src/fosslight_source/run_scanoss.py
Labels: enhancement

#59 Add license reference column
  src/fosslight_source/_scan_item.py
  src/fosslight_source/cli.py
  src/fosslight_source/run_scanoss.py
Labels: enhancement
