Repository fosslight/fosslight_source_scanner, pull requests merged in 2022-04, with the labels that each got.

#65 Add a commit message checker
  .github/workflows/pull-request.yml
Labels: chore

#66 Add a commit message checker
  .github/workflows/pull-request.yml
Labels: chore

#67 Fix errors that occur in Python 3.6.7 or lower
  requirements.txt
Labels: bug fix

#69 Add Dockerfile to build on ubuntu
  Dockerfile
  requirements.txt
Labels: enhancement

#71 Fix cli.py to remove redundant report
  src/fosslight_source/cli.py
  src/fosslight_source/run_scanoss.py
  tox.ini
Labels: bug fix
