Repository fosslight/fosslight_source_scanner, pull requests merged in 2023-08, with the labels that each got.

#128 Remove sorting
  src/fosslight_source/cli.py
Labels: chore

#129 Revert the scancode-toolkit version
  requirements.txt
Labels: bug fix

#130 Fix the util version
  requirements.txt
Labels: bug fix

#131 Load v32 and later of ScanCode
  src/fosslight_source/_license_matched.py
  src/fosslight_source/_parsing_scancode_file_item.py
  src/fosslight_source/_scan_item.py
Labels: enhancement

#132 Fix the scancdoe and util version
  requirements.txt
Labels: chore

#133 Priority change between Download Location extraction and scanner operation
  src/fosslight_source/_parsing_scancode_file_item.py
  src/fosslight_source/_scan_item.py
  src/fosslight_source/cli.py
  src/fosslight_source/run_scancode.py
  src/fosslight_source/run_spdx_extractor.py
  tests/cli_test.py
Labels: chore

#138 Fix vulnerability issue
  requirements.txt
Labels: bug fix
