Repository fosslight/fosslight_source_scanner, pull requests merged in 2024-07, with the labels that each got.

#164 Enable multiple input for -f and -o option
  requirements.txt
  src/fosslight_source/_help.py
  src/fosslight_source/cli.py
  src/fosslight_source/run_scancode.py
  src/fosslight_source/run_scanoss.py
  tox.ini
Labels: enhancement

#166 Check hidden files and mark 'Exlcude'.
  src/fosslight_source/_scan_item.py
Labels: chore

#165 Fix SPDX expression split bug
  src/fosslight_source/_parsing_scancode_file_item.py
Labels: bug

#168 Update scancode version for mac
  requirements.txt
Labels: bug fix

#167 Complying with SPDX License expression spec
  src/fosslight_source/_parsing_scancode_file_item.py
Labels: bug fix

#170 Version up FOSSLight util to fix default file bug
  requirements.txt
Labels: bug fix

#174 Add --ignore-cert-errors to ScanOSS command
  src/fosslight_source/run_scanoss.py
Labels: chore

#176 Modify error comment
  src/fosslight_source/cli.py
Labels: chore
