Repository fosslight/fosslight_source_scanner, pull requests merged in 2024-06, with the labels that each got.

#154 Supports for excluding paths
  requirements.txt
  src/fosslight_source/_help.py
  src/fosslight_source/_parsing_scanoss_file.py
  src/fosslight_source/cli.py
  src/fosslight_source/run_scancode.py
  src/fosslight_source/run_scanoss.py
  src/fosslight_source/run_spdx_extractor.py
  tox.ini
Labels: enhancement

#156 Modify column name
  src/fosslight_source/_parsing_scanoss_file.py
  src/fosslight_source/cli.py
Labels: chore

#157 Limit the maximum number of characters in the license
  src/fosslight_source/_scan_item.py
Labels: chore

#158 Move method to limit license characters
  src/fosslight_source/_scan_item.py
Labels: bug fix

#159 Bug fix related to license duplication
  src/fosslight_source/_scan_item.py
Labels: bug fix

#161 Update scancode version for web service
  requirements.txt
Labels: chore

#162 Amend exclude option
  src/fosslight_source/run_scancode.py
  src/fosslight_source/run_scanoss.py
Labels: bug fix
